let timeStamp = new Date().toLocaleString();
const content = [
  {
    id: "1",
    time: timeStamp,
    title: "Task1",
    description: "Description 1",
    dueDate: "8/20/2025, 11:00:00 AM",
    status: "Open",
    age: 10,
    tags: ["hard", "urgent"],
  },
  {
    id: "2",
    time: timeStamp,
    title: "Task2",
    description: "Description 2",
    dueDate: "11/20/2025, 11:00:00 AM",
    status: "Open",
    age: 10,
    tags: ["easy"],
  },
  {
    id: "3",
    time: timeStamp,
    title: "Task3",
    description: "Description 3",
    dueDate: "8/20/2025, 11:00:00 AM",
    status: "Open",
    age: 10,
    tags: ["Not", "Important"],
  },
  {
    id: "4",
    time: timeStamp,
    title: "Task4",
    description: "Description 4",
    dueDate: "18/20/2025, 11:00:00 AM",
    status: "Done",
    age: 10,
    tags: ["nice"],
  },
  {
    id: "5",
    time: timeStamp,
    title: "Task5",
    description: "Description 5",
    dueDate: "28/20/2025, 11:00:00 AM",
    status: "Working",
    age: 10,
    tags: ["nice", "developer"],
  },
  {
    id: "6",
    time: timeStamp,
    title: "Task6",
    description: "Description 6",
    dueDate: "1/20/2025, 11:00:00 AM",
    status: "Done",
    age: 10,
    tags: ["nice", "developer"],
  },
  {
    id: "7",
    time: timeStamp,
    title: "Task7",
    description: "Description 7",
    dueDate: "8/20/2025, 11:00:00 AM",
    status: "Working",
    age: 10,
    tags: ["nice", "developer"],
  },
];

export default content;
